/**
 * OCCUPRA RBAC — Permission Constants & Role Defaults
 * Single source of truth for all permission identifiers.
 */

const PERMISSIONS = {
  VIEW_ANALYTICS:   'VIEW_ANALYTICS',
  MANAGE_USERS:     'MANAGE_USERS',
  APPROVE_PROPERTY: 'APPROVE_PROPERTY',
  REJECT_PROPERTY:  'REJECT_PROPERTY',
  DELETE_PROPERTY:  'DELETE_PROPERTY',
  FEATURE_PROPERTY: 'FEATURE_PROPERTY',
  CREATE_PROPERTY:  'CREATE_PROPERTY',
  MANAGE_BOOKINGS:  'MANAGE_BOOKINGS',
};

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

/**
 * Default permission sets per role.
 * Used when a user's permissions[] is empty (existing accounts).
 */
const ROLE_DEFAULTS = {
  master_admin: ALL_PERMISSIONS,
  admin: [
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.APPROVE_PROPERTY,
    PERMISSIONS.REJECT_PROPERTY,
    PERMISSIONS.DELETE_PROPERTY,
    PERMISSIONS.FEATURE_PROPERTY,
    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.MANAGE_BOOKINGS,
  ],
  employee: [
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.APPROVE_PROPERTY,
    PERMISSIONS.REJECT_PROPERTY,
    PERMISSIONS.MANAGE_BOOKINGS,
  ],
  worker: [
    PERMISSIONS.VIEW_ANALYTICS,
  ],
};

module.exports = { PERMISSIONS, ALL_PERMISSIONS, ROLE_DEFAULTS };
